version: "3.5"
services:

  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
      - ./config/neo4j.conf:/conf/neo4j.conf

  salman:
    container_name: salman
    image: salman:dev
    build: ./salman
    env_file:
      - ./secrets/keys.env
      - ./config/salman.env
    volumes:
      - ./volumes/.cache:/home/salman/.cache

