version: "3.5"
services:

  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./docker/volumes/neo4j/data:/data
      - ./docker/volumes/neo4j/plugins:/plugins
      - ./docker/config/neo4j.conf:/conf/neo4j.conf

  salman:
    container_name: salman
    image: salman:dev
    build:
      dockerfile: docker/Dockerfile
    env_file:
      - ./docker/secrets/keys.env
      - ./docker/config/salman.env
    volumes:
      - ./docker/volumes/.cache:/home/salman/.cache

