version: "3.5"
services:
  nats:
    container_name: nats
    image: nats-salman:dev
    build: ./nats
    ports:
      - "443:443"
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./volumes/nats:/tmp/nats/jetstream

  transcriber:
    container_name: transcriber
    image: salman:dev
    build: ./salman
    env_file:
      - ./secrets/keys.env
      - ./config/nats.env
    entrypoint: workers transcription-worker
    volumes:
      - ./volumes/.cache:/home/salman/.cache

  segmenter:
    container_name: segmenter
    image: salman:dev
    build: ./salman
    env_file:
      - ./secrets/keys.env
      - ./config/nats.env
    entrypoint: workers segmentation-worker
    volumes:
      - ./volumes/.cache:/home/salman/.cache

  cleanup:
    container_name: cleanup
    image: salman:dev
    build: ./salman
    env_file:
      - ./secrets/keys.env
      - ./config/nats.env
    entrypoint: workers cleanup-worker
    volumes:
      - ./volumes/.cache:/home/salman/.cache

  # frontend:
  #   container_name: frontend
  #   image: salman-frontend:dev
  #   build:
  #     context: ./frontend
  #     dockerfile: docker/Dockerfile
  #   env_file:
  #     - ./config/nats.env
  #   volumes:
  #     - ./frontend:/app
  #     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/npm:/home/node/.npm
  #   restart: always
  #   ports:
  #     - 3000:3000
